### ISSUE TITLE
Don't update Version.lua unless lua code changes

### ISSUE THREAD

**Issue by jpuigcerver** [jpuigcerver/Laia#16]
Currently, every time a commit is made the Version.lua file is updated with the current date and time, even if no Lua code was modified. 

Although it is not very important, I would suggest to modify this behavior and update only the timestamp there when some lua file changes. I think we'll get cleaner diffs and better statistics with this change.

**Comment by mauvilsa** [comment]
I have modified the hook so that version is only updated when laia-* or *.lua files change.
