### ISSUE TITLE
torch-cuda/Dockerfile is redundant

### ISSUE THREAD

**Issue by dmas-at-wiris** [jpuigcerver/Laia#19]
[install.sh](https://raw.githubusercontent.com/torch/distro/master/install.sh) already creates (using luarocks) the following rocks: torch, cutorch, cunn and cudnn. So L38-L42 should be removed. 

This can potentially lead to problems. If a particular Torch7 version is checkout'd (at L29), the more recent version of the rocks will be installed, instead of the particular ones.

**Comment by dmartinalbo** [comment]
Done.
