### ISSUE TITLE
Missing MDRNN.lua file

### ISSUE THREAD

**Issue by bdotgradb** [jpuigcerver/Laia#20]
Running the installation command leads to a missing file error:

$ luarocks install https://raw.githubusercontent.com/jpuigcerver/Laia/master/rocks/laia-scm-1.rockspec
Using https://raw.githubusercontent.com/jpuigcerver/Laia/master/rocks/laia-scm-1.rockspec... switching to 'build' mode
Cloning into 'Laia'...
remote: Counting objects: 248, done.
remote: Compressing objects: 100% (212/212), done.
remote: Total 248 (delta 43), reused 133 (delta 19), pack-reused 0
Receiving objects: 100% (248/248), 1.13 MiB | 18.00 KiB/s, done.
Resolving deltas: 100% (43/43), done.
Checking connectivity... done.
cp: cannot stat 'laia/nn/MDRNN.lua': No such file or directory

Error: Build error: Failed installing laia/nn/MDRNN.lua in /home/andrew/torch/install/lib/luarocks/rocks/laia/scm-1/lua/laia/nn/MDRNN.lua

Which seems to be from this line: https://github.com/jpuigcerver/Laia/blob/master/rocks/laia-scm-1.rockspec#L58

**Comment by jpuigcerver** [comment]
@mauvilsa could you fix the docker? I removed the MDRNN.lua file because it was not well implemented and nobody was using it anyway.

**Comment by mauvilsa** [comment]
Removed MDRNN.lua from the rockspec and updated the docker image in docker hub.
