### ISSUE TITLE
No LuaRocks module found for laia.util.mem

### ISSUE THREAD

**Issue by bdotgradb** [jpuigcerver/Laia#21]
In my install/share/lua/5.1/laia/util directory I see the 13 files corresponding to:
    ["laia.util.argparse"] = "laia/util/argparse.lua",
    ["laia.util.base"] = "laia/util/base.lua",
    ["laia.util.cudnn"] = "laia/util/cudnn.lua",
    ["laia.util.decode"] = "laia/util/decode.lua",
    ["laia.util.format"] = "laia/util/format.lua",
    ["laia.util.io"] = "laia/util/io.lua",
    ["laia.util.log"] = "laia/util/log.lua",
    ["laia.util.math"] = "laia/util/math.lua",
    ["laia.util.rand"] = "laia/util/rand.lua",
    ["laia.util.string"] = "laia/util/string.lua",
    ["laia.util.table"] = "laia/util/table.lua",
    ["laia.util.torch"] = "laia/util/torch.lua",
    ["laia.util.types"] = "laia/util/types.lua"

but when I try and run the laia-create-model for the Spanish Numbers experiment it complains that it cannot find laia.util.mem

**Comment by mauvilsa** [comment]
Thank you for reporting this @bdotgradb. I have fixed it. Try again to see if the Spanish Numbers example works for you now.

**Comment by bdotgradb** [comment]
That worked - next I get: Optional lua module "alarm" not found!
and: malformed --batch_size: value "" is not an integer
because in the example given it appears as:  --batch_size "$batch_size"
but the variable is never defined (from the run.sh script it looks like it should be set to 16).

How/from where do I install the alarm module?

**Comment by jpuigcerver** [comment]
Hi,

alarm is not mandatory, although I would recommend to install it. Just type:

```
luarocks install lalarm
```

Regarding the batch size, you should set the value to `batch_size` to an appropriate numeric value. We typically use 16 for our experiments, but this number may depends on the available memory of your GPU.

**Comment by bdotgradb** [comment]
Thanks! Re the batch_size, I've submitted a PR to update the readme.
