### ISSUE TITLE
IAM - Missing file - all.txt

### ISSUE THREAD

**Issue by bdotgradb** [jpuigcerver/Laia#23]
For the IAM example, the first two commands complete successfully but the third command results in an error: 
./steps/download.sh --iam_user "$IAM_USER" --iam_pass "$IAM_PASS";
./steps/prepare_images.sh;
./steps/prepare_iam_text.sh --partition aachen;
   awk: cannot open data/lang/lines/char/all.txt (No such file or directory)
   ERROR: Creating file data/lang/lines/char/all_wspace.txt

**Comment by bdotgradb** [comment]
OK, I think I found the problems and resolved them. Please review https://github.com/jpuigcerver/Laia/pull/24

**Comment by jpuigcerver** [comment]
Thank you so much for spotting all these bugs.
