### ISSUE TITLE
ERROR: Creating file "data/lang/forms/word/aachen/tr.txt"!

### ISSUE THREAD

**Issue by miliadis** [jpuigcerver/Laia#26]
Hey @jpuigcerver 

One more issue I found when I run: 

./steps/prepare_iam_text.sh --partition aachen;
awk: line 2: syntax error at or near ,
awk: line 7: syntax error at or near else
awk: line 10: syntax error at or near }
ERROR: Creating file "data/lang/forms/word/aachen/tr.txt"!

I had that issue on my previous run as well, but I workaround it by not creating tr.txt file for words. Since I am creating data again I would like to know why this issue happen.

Thanks!

**Comment by jpuigcerver** [comment]
Mmmm... I did not experience any problem with this. Maybe it has to do with the version of awk and the syntax for the `match()` function in that specific version. I am using GNU awk 4.1.3, could you please tell me your version?

**Comment by mauvilsa** [comment]
It is normal that in default installations the awk command does not correspond to GNU awk. In the scripts instead of using awk it could be better to use gawk so that it is explicit that the GNU awk extensions are required.

**Comment by miliadis** [comment]
@jpuigcerver @mauvilsa 

gawk solved the issue!

**Comment by jpuigcerver** [comment]
FYI: I just committed a change to use gawk in all scripts instead of awk, which as @miliadis pointed, is not equivalent in all systems.
