### ISSUE TITLE
Prepare image error from egs/iam

### ISSUE THREAD

**Issue by yanyufish** [jpuigcerver/Laia#31]
Hi,

I am using ImageMagick6 and at the step of preparing image by running `./steps/prepare_images.sh`, I got the following error. Do you have any idea? Thanks.

> Failed image processing:
> imgtxtenh: enhancing by Sauvola: width=80pixels, mfct=0.2, sfct=0.5
> imgtxtenh: removed 1 small components from a total of 18 (min. area: 6 pixels^2)
> convert: magick/cache.c:306: AddOpenCLEvent: Assertion `cache_info->opencl != (OpenCLCacheInfo *) ((void *)0)' failed.
> ./steps/prepare_images.sh: line 40:  1669 Done                    imgtxtenh -d 118.110 "$1" png:-
>       1670 Aborted                 (core dumped) | convert png:- -deskew 40% -bordercolor white -border 5 -trim -bordercolor white -border 20x0 +repage -strip "data/imgs/$partition/$bn.jpg"
> ERROR: Processing image data/original/lines/a01-000u-00.png

**Comment by mauvilsa** [comment]
Can you give more details about your environment? Like what OS, how image magick was installed, etc.

**Comment by mauvilsa** [comment]
I have never tested installing ImageMagick from source. Anyway from what you say it is not possible for me to reproduce the error. Could you isolate the problem (exact command and image that fails) and maybe create a docker file that performs the exact installation that you did and that reproduces the error?

**Comment by yanyufish** [comment]
After reinstalling ImageMagick using apt-get install, the error went away. Thanks.
