### ISSUE TITLE
 module 'trepl' not found:

### ISSUE THREAD

**Issue by ricardobnjunior** [jpuigcerver/Laia#32]
I am having an error:

to try solved it, i put the trepl folder into the steps folder, but the error has persist

./steps/train_lstm1d.sh/train/aachen/lstm1d_h128.t7
/usr/bin/luajit: /usr/lib/torch-trepl/th:103: module 'trepl' not found:
	no field package.preload['trepl']
	no file '/home/suporte/Área de Trabalho/LAIA/Laia-master/egs/iam/../../trepl/init.lua'
	no file '/home/suporte/Área de Trabalho/LAIA/Laia-master/egs/iam/../../trepl.lua'
	no file './trepl.so'
	no file '/usr/local/lib/lua/5.1/trepl.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.1/trepl.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/lib/torch-trepl/th:103: in main chunk
	[C]: at 0x55ce9144b1d0

Please can somebody help me ?

**Comment by jpuigcerver** [comment]
You need to install the Lua trepl module. 

https://www.google.es/search?q=trepl+lua
