### ISSUE TITLE
2D-LSTM

### ISSUE THREAD

**Issue by habibai** [jpuigcerver/Laia#35]
Hello and thanks for your great work!

I am going to train the 2D-LSTM model but the file "create-model-aachen.lua" is missing. Do you have any implementation of 2D-LSTM model for handwriting recognition?

Thanks

**Comment by jpuigcerver** [comment]
Hi,

Laia does not support 2D-LSTM models. 

The script that you are referring to is an old relic that it's not supported by Laia anymore. During some time while we were developing Laia, I added some support to 2D-LSTMs that I needed to work on a paper. But at the end I ended up using RETURNN (https://github.com/rwth-i6/returnn) to run the experiments with 2D-LSTMs.
