### ISSUE TITLE
problem in decode_net.sh

### ISSUE THREAD

**Issue by rafikg** [jpuigcerver/Laia#38]
@jpuigcerver 
I am running the Laia using my own dataset which is formatted as in Bentham dataset. The training is running good but when I run the decode code on test and validation parts, I get an error:
```
hyp[line[0]] = line[1:]
IndexError: list index out of range
```
I checked and It seems that the decode/no_lm/char/va_*.txt  decode/no_lm/char/te_*.txt contains space lines which gives the error above!  
I added this line in compute-errors.py 
```
for line in args.hypothesis:                                                                                                           │
        line = line.split()                                                                                                                │
        if len(line)!=0:                                                                                                                   │
           hyp[line[0]] = line[1:] 
```
The code is running but it does not show anything!!!

**Comment by jpuigcerver** [comment]
Hi, sorry for the late reply.

- Can you point to the specific file and line that raises the exception?
- Can I access your reference text files for validation/test?

**Comment by rafikg** [comment]
Thanks @jpuigcerver . there is no errors. Actually, the errors is coming fro  my side because i changed a little bit the decode script. So, your code is fine and consistent. Thanks.
