### ISSUE TITLE
Trained Model for testing on sample pages

### ISSUE THREAD

**Issue by mineshmathew** [jpuigcerver/Laia#39]
Is there any trained model available so that I can run the HTR on a few English handwritten pages.
--
thanks

**Comment by jpuigcerver** [comment]
You can use the model trained on IAM, from the paper https://ieeexplore.ieee.org/abstract/document/8269951/:

https://www.prhlt.upv.es/~jpuigcerver/IAM_lstm1d_h128_batchnorm_distortions_cnn_16_32_48_64_80_dropout_0.2_rnn_5x256_80epochs.t7.gz

**Comment by mineshmathew** [comment]
@jpuigcerver Thank you for sharing the model. I was able to run the laia-decode function on my line image. The output I get is as follows ( for a single line image)
`1_1_0_line0_gray_128h 67 42 36 1 64 68 32 32 36 64 64 1 56 38 1 28 54 76 1 58 28 66 62 56 40 36 52 1 34 36 28 54 34`

I guess what I get there as transcription is a sequence of label ids. Can you please tell me how I get the ascii/unicode characters from these ids. I suppose there is a symbol table., which you used to train the given model file. 

thanks

**Comment by mineshmathew** [comment]
I was able to get syms.txt file by running the data preparation steps for IAM ( egs/iam/ )..thank you. I will try with this list
