### ISSUE TITLE
<eps> symbol

### ISSUE THREAD

**Issue by habibai** [jpuigcerver/Laia#40]
Hi there

I have a question, what is the "eps" symbol you add to syms.txt file? I know you add "ctc" for blank and "space" for space but I didn't see any explanation about "eps". 

Thanks

**Comment by jpuigcerver** [comment]
This symbol is not used for CTC training or decoding, but it is used when one wants to combine the output of the neural network with language models (typically using Kaldi).

More specifically, it is used in the arcs of finite state transducers (FSTs) to indicate that no input is consumed or nor output is produced for that arc.
