### ISSUE TITLE
Using language modelling with word level recognition

### ISSUE THREAD

**Issue by dutta1kartik3** [jpuigcerver/Laia#41]
Hi @jpuigcerver,
Could you please point me to how I could modify the existing Laia framework to create a character-level language model which I could use for decoding the output of a word-level recognition system based on IAM? (similarly to how currently a word-level language model is used with line-level recognizer, say for IAM)
Thanks

**Comment by jpuigcerver** [comment]
Hi,

In https://github.com/jpuigcerver/Laia/tree/master/egs/iam/utils you have scripts to create a character-level language model, and decode images using it. 

In particular: 
https://github.com/jpuigcerver/Laia/blob/master/egs/iam/utils/build_char_lm.sh
https://github.com/jpuigcerver/Laia/blob/master/egs/iam/utils/build_char_fsts.sh

However, these scripts are not very well tested, so I cannot guarantee that they are bug-free and work well.

If you have any more concrete question, please re-open the issue and I'll try to address it.
