### ISSUE TITLE
Rimes Dataset not accessible anymore

### ISSUE THREAD

**Issue by elnazsn1988** [jpuigcerver/Laia#44]
Hi All - Ive been trying to get access to the RImes Dataset and have signed and sent the NDA - no luck so far. Is there an altenative Repo available?

**Comment by jpuigcerver** [comment]
Not that I am aware of 🤔.

**Comment by elnazsn1988** [comment]
> Not that I am aware of 🤔.

thanks for your response, may I ask at what date did the a2ai website respond to your NDA and give you access - am trying to understand whether theres an issue with my NDA or if the dataset is no longer available, as Mitek acquired a2ai

**Comment by jpuigcerver** [comment]
Mmm... I think it took about a week or so, but this was a long time ago, when I was doing my PhD.

**Comment by bilalltf** [comment]
The same issue: data link isn't working (This site can’t be reached)

**Comment by bilalltf** [comment]
![image](https://user-images.githubusercontent.com/56886792/159736791-2d7d2206-3a75-4684-900e-164034785507.png)

**Comment by jpuigcerver** [comment]
It seems that A2IA, the company that hosted the data, was bought by Mitek and they decided to remove the data (or at least change the links). So, there's really nothing that I can do about it.
