### ISSUE TITLE
Process mini-batch as N blocks to reduce GPU memory usage

### ISSUE THREAD

**Issue by mauvilsa** [jpuigcerver/Laia#9]
In train.lua, provide the possibility to divide each mini-batch in N blocks, processing each block in GPU sequentially. This is so that training can be performed for large mini-batches (relative to the amount of GPU memory) in GPUs with limited memory, or to leave room for other processes using the GPU.

**Comment by jpuigcerver** [comment]
@mauvilsa I'm not sure if you are aware, but I implemented this feature a few months ago. The CTCTrainer class accepts an argument (batchChunkSize, or --batch_chunk_size from the command line), to split the batch in each iteration into a variable number of chunks of batch_chunk_size MB. This is useful to limit the maximum amount of MB to process in each batch.

The gradients are accumulated among all chunks to perform a single parameter update.

**Comment by mauvilsa** [comment]
Nice! I will try to test this soon.
